events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;


    # 123Блокируем ботов по User-Agent
    map $http_user_agent $blocked_ua {
        default 0;
        ~*libredtail-http 1;
        ~*zgrab 1;
        ~*masscan 1;
        ~*nmap 1;
        ~*ThinkPHP 1;
        ~*Go-http-client 1;
    }

    server {
         listen 443 ssl;
        server_name demo555.publicvm.com;
        root /usr/share/nginx/html;

        ssl_certificate /etc/letsencrypt/live/demo555.publicvm.com/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/demo555.publicvm.com/privkey.pem;

        # Блокируем по User-Agent
        if ($blocked_ua) {
            return 444;
        }

        # Блокируем любые запросы к подозрительным путям
       location = / {
           try_files /index.html =444;
       }
       location / {
           return 444;
       }

        # API
        location /api {
            proxy_pass https://quiz_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        #  Хелсчек
        location /nginx-health {
            access_log off;
            add_header Content-Type text/plain;
            return 200 "nginx ok\n";
        }
    }
}