events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;

        # Главная страница
        location / {
            try_files $uri /index.html;
        }

        # Статические файлы
        location ~ \.(js|css|html|ico)$ {
            try_files $uri =404;
        }

        # API
        location /api {
            proxy_pass http://backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
