version: "3.8"
services:
  gatus:
    image: twinproduction/gatus:v5.8.0
    container_name: gatus
    env_file: ../.env          # читаем тот же .env
    volumes:
      - ./config.yml:/config/config.yml
    ports:
      - 127.0.0.1:8085:8080
    restart: unless-stopped