name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Compose build
        run: docker compose build

      - name: Copy .env on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/java_quiz_app
            cat > .env <<EOF
            DB_ROOT_PASS=${{ secrets.DB_ROOT_PASS }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            OPENROUTER_KEY=${{ secrets.OPENROUTER_KEY }}
            CORS_ORIGINS=https://185.250.44.34
            EOF

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/java_quiz_app
            git pull
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f