name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Compose build
        run: docker compose build

      - name: Copy .env on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/java_quiz_app
            cat > .env <<EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            DB_ROOT_PASS=${{ secrets.DB_ROOT_PASS }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            OPENROUTER_KEY=${{ secrets.OPENROUTER_KEY }}
            CORS_ORIGINS=https://yourdomain.com
            AI_API_URL=${{ secrets.AI_API_URL }}
            AI_API_MODEL=${{ secrets.AI_API_MODEL }}
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            TELEGRAM_CHAT=${{ secrets.TELEGRAM_CHAT }}
            BASE_URL=${{ secrets.BASE_URL }}
            
            
            EOF

      - name: Deploy main stack
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/java_quiz_app
            git pull
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f
            
      - name: Deploy monitoring stack
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/java_quiz_app
            docker compose -f monitoring/docker-compose.yml up -d